[project]
name = "polynomial-table"
description = "A Clarity smart contract for managing polynomial-based computational tables and access control"
authors = ["Polynomial Labs"]
telemetry = false
requirements = []

[contracts.polynomial-access]
path = "contracts/polynomial-access.clar"
depends-on = ["polynomial-registry"]
[contracts.polynomial-registry]
path = "contracts/polynomial-registry.clar"
depends-on = []

[repl.analysis]
passes = ["check_checker"]

[repl]
costs_version = 2
parser_version = 2


[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
